apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: archontos-default-deny
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: archontos
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: archontos
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: archontos
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
